import { v4 as uuid } from "uuid";
import {
  lens85mm,
  actionCamera,
  actionCamera2,
  actionCamera3,
  cameraCanon,
  cameraCanon2,
  cameraCanon3,
  cameraCanon4,
  cameraCanon5,
  canon6dCamera,
  canon6dCamera2,
  canon6dCamera3,
  canon6dCamera4,
  canon6dCamera5,
  lensForMobile,
  lensForMobile2,
  lensForMobile3,
  lensForMobile4,
  lensForMobile5,
  polaroidCamera,
  polaroidCamera2,
  polaroidCamera3,
  polaroidCamera4,
  polaroidCamera5,
  sonyAlphaCamera,
  sonyAlphaCamera2,
  sonyAlphaCamera3,
  sonyAlphaCamera4,
  sonyAlphaCamera5,
  sonySmallCamera,
  sonySmallCamera2,
  sonySmallCamera3,
  sonySmallCamera4,
} from "../../Data/Img/Products/ProductImages";

/*
  Product Database 
*/

const products = [
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony DSC W830 Cyber-Shot 20.1 MP Point & Shoot Camera",
    price: 10999,
    rating: 4,
    totalRating: 13,
    wishlist: false,
    src1: sonySmallCamera,
    src2: sonySmallCamera2,
    src3: sonySmallCamera3,
    src4: sonySmallCamera4,
    src5: sonySmallCamera,
    inStock: 20,
    newestArrival: true,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Super HAD CCD sensor with 20.1 effective megapixels : Included Components - 1 U (Including-Rechargeable battery, AC Adaptor, Multi USB Cable, Wrist Strap,User Manual)",
      "720p MP4 movie mode the camera shoots 1280 x 720 high definition movies at 30 fps, Focal length f=4.5-36mm. Exposure Compensation: +/- 2.0 EV, 1/3 EV step",
      "8x optical zoom Carl Zeiss Vario Tessar lens.Refer user manual ; Screen type: 6.7cm(2.7-type)(4:3) / 230,400 dots / ClearPhoto / TFT LCD ; Brightness Control: 5 (Bright) / 4 / 3 / 2 / 1 (Dark)",
      "Equipped with sweep panorama, intelligent auto and picture effect, Self-Timer: Off , 10sec., 2sec., portrait1, portrait2",
      "Power Consumption (Camera Mode): Approx. 1.2W; Power Source: DC3.6V (supplied battery)/DC5.0V (supplied AC adaptor)",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 6D DSLR Camera (Kit 24 - 105)  (Black)",
    price: 135100,
    rating: 4.5,
    totalRating: 40,
    wishlist: false,
    src1: canon6dCamera,
    src2: canon6dCamera2,
    src3: canon6dCamera3,
    src4: canon6dCamera4,
    src5: canon6dCamera5,
    inStock: 13,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "This camera comes with a high resolution 20.2-megapixel CMOS sensor capture sharp images with quality and detail. It has a new photodiode construction, gapless microlens array and on-chip noise reduction circuitry on the sensor to keep the image data clean and clear, even at high ISO settings.",
      "The Canon EOS 6D lets you take pictures in any environment, bright or low-lit, as it comes with a flexible ISO speed setting between 50 and 102400. It lets you adjust the camera's sensitivity to light, giving you great photos in both day and night.",
      "As the Canon EOS 6D supports IEEE 802.11 b/g/n networks, you share data between your camera and Wi-Fi enabled devices or on social networking sites. With built-in GPS tracking, you can tag the place where you took the photo with accurate GPS coordinates. You can also use your smartphone to remotely control the camera through Wi-Fi.",
      "Record high definition videos with manual exposure control and multiple frame rates. Record 1080p videos at 30 frames per second or 720p videos at 60 frames per second.",
      "High Dynamic Range lets you take high-quality videos with ease, allowing you to expand your creative mindset using various features such as Scene Intelligent Auto and Special Scene Modes to get the perfect shot.",
      "This camera is compatible with SD/SDHC/SDXC memory cards, allowing you to store more photos and videos.",
    ],
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "canon",
    title: "Canon EF 85mm f1.2L II USM Lens for Canon DSLR Cameras",
    price: 85100,
    rating: 4.2,
    totalRating: 13,
    wishlist: false,
    src1: lens85mm,
    src2: lens85mm,
    src3: lens85mm,
    src4: lens85mm,
    src5: lens85mm,
    inStock: 3,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Beautiful bokeh with DS* coating",
      "High image quality and bright f/1.2 aperture mid-telephoto zoom RF L lens.",
      "Blue spectrum refractive optics (br) Reduces chromatic aberration.",
      "Minimum focusing distance of 2.79 ft./0.85M.",
      "Control ring for direct setting changes.",
      "Lens Type: Macro",
    ],
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "papa",
    title: "Apexel 4K HD Mobile Phone 5-in-1 Camera Lens Kit",
    price: 350,
    rating: 1,
    totalRating: 25,
    wishlist: false,
    src1: lensForMobile,
    src2: lensForMobile2,
    src3: lensForMobile3,
    src4: lensForMobile4,
    src5: lensForMobile5,
    inStock: 0,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "The 4K HD Mobile Phone 5-in-1 Camera Lens Kit from Apexel is a bundle that contains a 2x Zoom Telephone Lens, a 0.6x / 110° Wide-Angle Lens, a 170° Super Wide-Angle Lens, a 195° Fisheye Lens, and a 10x Macro Lens. These lenses are compatible with iPhone XS Max, XR, X, 8, 7, and 6 Plus, as well as Samsung phones.",
      "This lens provides a magnification of 10x for detailed close-ups. The Telephoto Lens provides a minimum magnification of 2x to deliver photos from a distance that are of higher quality. If you'd like to create subjects with a blurred background, please keep the lens 12 to 40 from your subject. To fully utilize the 2x magnification, keep the lens at least 60 from the subject.",
      "Shoot a wide range of scenery with a magnification of 0.6x and a 110° angle of view. This lens is suitable for group selfies, travel, landscapes, and more.",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "polaroid",
    title: "Polaroid Originals Now I-Type Instant Camera - (9030)",
    price: 12999,
    rating: 1.8,
    totalRating: 14,
    wishlist: false,
    src1: polaroidCamera,
    src2: polaroidCamera2,
    src3: polaroidCamera3,
    src4: polaroidCamera4,
    src5: polaroidCamera5,
    inStock: 4,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "NOW: Polaroid's new point-and-shoot analog instant camera has all you need to catch every life moment in an original Polaroid photograph.",
      "NEW & IMPROVED: Now with autofocus, it’s simple to capture moments as you see them, so you can relive them forever in sharp, vivid color.",
      " DOUBLE EXPOSURE: Frame two moments in one with double exposure, or get yourself in the picture with self-timer and an accurate flash to make everyone look like they should.",
      "COLORFUL FUN: Now is available in the 7 colors of the iconic Polaroid spectrum.",
      " POINT. SHOOT. KEEP FOREVER: Now is compatible with both i-Type and 600 film.",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony Alpha ILCE-7RM3A Full-Frame 42.4MP Mirrorless Camera Body",
    price: 202900,
    rating: 2.8,
    totalRating: 34,
    wishlist: false,
    src1: sonyAlphaCamera,
    src2: sonyAlphaCamera2,
    src3: sonyAlphaCamera3,
    src4: sonyAlphaCamera4,
    src5: sonyAlphaCamera5,
    inStock: 12,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "35mm full-frame “Exmor R” CMOS sensor with approx 42.4 effective megapixels",
      "Enhanced BIONZ X image processing engine with front end LSI",
      "ISO sensitivity: 100 – 32000 (expandable 50 – 102400)",
      "14bit RAW format (ARW)",
      "Image sensor-shift mechanism (5-axis compensation) of a 5.5 stop compensation performance",
      "No optical low-pass filter",
      "Pixel Shift Multi Shooting",
      "Continuous shooting at up to 10 fps (with AF/AE tracking)",
      "Silent and vibration-free shooting (Electronical shutter)",
      "2 Year standard warranty + 1 year extended warranty on registration on alpha community",
      "399 points Hybrid Phase Detection AF + 425 Contrast AF",
      "Country of Origin: China",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 1500D 24.1 Digital SLR Camera EF S18-55 is II Lens",
    price: 18999,
    rating: 3.5,
    totalRating: 30,
    wishlist: false,
    src1: cameraCanon,
    src2: cameraCanon2,
    src3: cameraCanon3,
    src4: cameraCanon4,
    src5: cameraCanon5,
    inStock: 0,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Sensor: APS-C CMOS Sensor with 24.1 MP (high resolution for large prints and image cropping). Transmission frequency (central frequency):Frequency: 2 412 to 2 462MHz. Standard diopter :-2.5 - +0.5m-1 (dpt)",
      "ISO: 100-6400 sensitivity range (critical for obtaining grain-free pictures, especially in low light)",
      "Image Processor: DIGIC 4+ with 9 autofocus points (important for speed and accuracy of autofocus and burst photography)",
      "Video Resolution: Full HD video with fully manual control and selectable frame rates (great for precision and high-quality video work)",
      " Connectivity: WiFi, NFC and Bluetooth built-in (useful for remotely controlling your camera and transferring pictures wirelessly as you shoot)",
      "Lens Mount: EF-S mount compatible with all EF and EF-S lenses (crop-sensor mount versatile and compact, especially when used with EF-S lenses)",
      "Country of Origin: Taiwan",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "gopro",
    title: "GoPro HERO10 Black - Front LCD and Touch Rear Screens,23MP.",
    price: 35400,
    rating: 4.5,
    totalRating: 103,
    wishlist: false,
    src1: actionCamera,
    src2: actionCamera2,
    src3: actionCamera3,
    src4: actionCamera,
    src5: actionCamera2,
    inStock: 10,
    newestArrival: true,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "1 year international + 1 year local India warranty. For 1 Year extended warranty please visit gopro.luxurypersonified.co.in",
      "Revolutionary Processor: Faster. Smoother. Better. The powerful new GP2 engine changes the game—snappy performance, responsive touch controls and double the frame rate for amazingly smooth footage. Designed specifically for the demanding nature of the GoPro, the GP2 “system on a chip” is by far our fastest ever.",
      "High-Res Photos + Videos, High Frame Rate: Step up to the sharpest-shooting GoPro ever. Upgraded to incredible 23MP photos and 5.3K video resolution at 60fps, HERO10 offers double the frame rate for amazingly smooth motion. Plus, there’s 8x slo-mo at 2.7K and you can pause videos and grab 15.8MP still photos from 5.3K video that look amazing.",
      "Unbelievable Image Quality: Shoot with fine detail, realistic textures and stunning contrast, even in low light. Images look their best thanks to a new water-shedding hydrophobic lens cover that repels water while helping to eliminate lens flare and other artifacts.",
      "HyperSmooth 4.0: HyperSmooth has never been smoother, and it’s easy to dial in the best stabilization at all times. Plus, get even better low-light performance and horizon leveling with a higher tilt limit, so your footage looks perfectly straight when you want it.",
      "Compatible with Over 30 Accessories",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony DSC W830 Cyber-Shot 20.1 MP Point & Shoot Camera",
    price: 10999,
    rating: 4.8,
    totalRating: 13,
    wishlist: false,
    src1: sonySmallCamera,
    src2: sonySmallCamera2,
    src3: sonySmallCamera3,
    src4: sonySmallCamera4,
    src5: sonySmallCamera,
    inStock: 0,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Super HAD CCD sensor with 20.1 effective megapixels : Included Components - 1 U (Including-Rechargeable battery, AC Adaptor, Multi USB Cable, Wrist Strap,User Manual)",
      "720p MP4 movie mode the camera shoots 1280 x 720 high definition movies at 30 fps, Focal length f=4.5-36mm. Exposure Compensation: +/- 2.0 EV, 1/3 EV step",
      "8x optical zoom Carl Zeiss Vario Tessar lens.Refer user manual ; Screen type: 6.7cm(2.7-type)(4:3) / 230,400 dots / ClearPhoto / TFT LCD ; Brightness Control: 5 (Bright) / 4 / 3 / 2 / 1 (Dark)",
      "Equipped with sweep panorama, intelligent auto and picture effect, Self-Timer: Off , 10sec., 2sec., portrait1, portrait2",
      "Power Consumption (Camera Mode): Approx. 1.2W; Power Source: DC3.6V (supplied battery)/DC5.0V (supplied AC adaptor)",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 6D DSLR Camera (Kit 24 - 105)  (Black)",
    price: 135100,
    rating: 3.3,
    totalRating: 40,
    wishlist: false,
    src1: canon6dCamera,
    src2: canon6dCamera2,
    src3: canon6dCamera3,
    src4: canon6dCamera4,
    src5: canon6dCamera5,
    inStock: 6,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "This camera comes with a high resolution 20.2-megapixel CMOS sensor capture sharp images with quality and detail. It has a new photodiode construction, gapless microlens array and on-chip noise reduction circuitry on the sensor to keep the image data clean and clear, even at high ISO settings.",
      "The Canon EOS 6D lets you take pictures in any environment, bright or low-lit, as it comes with a flexible ISO speed setting between 50 and 102400. It lets you adjust the camera's sensitivity to light, giving you great photos in both day and night.",
      "As the Canon EOS 6D supports IEEE 802.11 b/g/n networks, you share data between your camera and Wi-Fi enabled devices or on social networking sites. With built-in GPS tracking, you can tag the place where you took the photo with accurate GPS coordinates. You can also use your smartphone to remotely control the camera through Wi-Fi.",
      "Record high definition videos with manual exposure control and multiple frame rates. Record 1080p videos at 30 frames per second or 720p videos at 60 frames per second.",
      "High Dynamic Range lets you take high-quality videos with ease, allowing you to expand your creative mindset using various features such as Scene Intelligent Auto and Special Scene Modes to get the perfect shot.",
      "This camera is compatible with SD/SDHC/SDXC memory cards, allowing you to store more photos and videos.",
    ],
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "canon",
    title: "Canon EF 85mm f1.2L II USM Lens for Canon DSLR Cameras",
    price: 85100,
    rating: 3.2,
    totalRating: 13,
    wishlist: false,
    src1: lens85mm,
    src2: lens85mm,
    src3: lens85mm,
    src4: lens85mm,
    src5: lens85mm,
    inStock: 7,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Beautiful bokeh with DS* coating",
      "High image quality and bright f/1.2 aperture mid-telephoto zoom RF L lens.",
      "Blue spectrum refractive optics (br) Reduces chromatic aberration.",
      "Minimum focusing distance of 2.79 ft./0.85M.",
      "Control ring for direct setting changes.",
      "Lens Type: Macro",
    ],
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "papa",
    title: "Apexel 4K HD Mobile Phone 5-in-1 Camera Lens Kit",
    price: 299,
    rating: 2.7,
    totalRating: 25,
    wishlist: false,
    src1: lensForMobile,
    src2: lensForMobile2,
    src3: lensForMobile3,
    src4: lensForMobile4,
    src5: lensForMobile5,
    inStock: 6,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "The 4K HD Mobile Phone 5-in-1 Camera Lens Kit from Apexel is a bundle that contains a 2x Zoom Telephone Lens, a 0.6x / 110° Wide-Angle Lens, a 170° Super Wide-Angle Lens, a 195° Fisheye Lens, and a 10x Macro Lens. These lenses are compatible with iPhone XS Max, XR, X, 8, 7, and 6 Plus, as well as Samsung phones.",
      "This lens provides a magnification of 10x for detailed close-ups. The Telephoto Lens provides a minimum magnification of 2x to deliver photos from a distance that are of higher quality. If you'd like to create subjects with a blurred background, please keep the lens 12 to 40 from your subject. To fully utilize the 2x magnification, keep the lens at least 60 from the subject.",
      "Shoot a wide range of scenery with a magnification of 0.6x and a 110° angle of view. This lens is suitable for group selfies, travel, landscapes, and more.",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "polaroid",
    title: "Polaroid Originals Now I-Type Instant Camera - (9030)",
    price: 12999,
    rating: 2.6,
    totalRating: 14,
    wishlist: false,
    src1: polaroidCamera,
    src2: polaroidCamera2,
    src3: polaroidCamera3,
    src4: polaroidCamera4,
    src5: polaroidCamera5,
    inStock: 3,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "NOW: Polaroid's new point-and-shoot analog instant camera has all you need to catch every life moment in an original Polaroid photograph.",
      "NEW & IMPROVED: Now with autofocus, it’s simple to capture moments as you see them, so you can relive them forever in sharp, vivid color.",
      " DOUBLE EXPOSURE: Frame two moments in one with double exposure, or get yourself in the picture with self-timer and an accurate flash to make everyone look like they should.",
      "COLORFUL FUN: Now is available in the 7 colors of the iconic Polaroid spectrum.",
      " POINT. SHOOT. KEEP FOREVER: Now is compatible with both i-Type and 600 film.",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony Alpha ILCE-7RM3A Full-Frame 42.4MP Mirrorless Camera Body",
    price: 202900,
    rating: 4.7,
    totalRating: 34,
    wishlist: false,
    src1: sonyAlphaCamera,
    src2: sonyAlphaCamera2,
    src3: sonyAlphaCamera3,
    src4: sonyAlphaCamera4,
    src5: sonyAlphaCamera5,
    inStock: 4,
    newestArrival: true,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "35mm full-frame “Exmor R” CMOS sensor with approx 42.4 effective megapixels",
      "Enhanced BIONZ X image processing engine with front end LSI",
      "ISO sensitivity: 100 – 32000 (expandable 50 – 102400)",
      "14bit RAW format (ARW)",
      "Image sensor-shift mechanism (5-axis compensation) of a 5.5 stop compensation performance",
      "No optical low-pass filter",
      "Pixel Shift Multi Shooting",
      "Continuous shooting at up to 10 fps (with AF/AE tracking)",
      "Silent and vibration-free shooting (Electronical shutter)",
      "2 Year standard warranty + 1 year extended warranty on registration on alpha community",
      "399 points Hybrid Phase Detection AF + 425 Contrast AF",
      "Country of Origin: China",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 1500D 24.1 Digital SLR Camera EF S18-55 is II Lens",
    price: 18999,
    rating: 2.5,
    totalRating: 30,
    wishlist: false,
    src1: cameraCanon,
    src2: cameraCanon2,
    src3: cameraCanon3,
    src4: cameraCanon4,
    src5: cameraCanon5,
    inStock: 5,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Sensor: APS-C CMOS Sensor with 24.1 MP (high resolution for large prints and image cropping). Transmission frequency (central frequency):Frequency: 2 412 to 2 462MHz. Standard diopter :-2.5 - +0.5m-1 (dpt)",
      "ISO: 100-6400 sensitivity range (critical for obtaining grain-free pictures, especially in low light)",
      "Image Processor: DIGIC 4+ with 9 autofocus points (important for speed and accuracy of autofocus and burst photography)",
      "Video Resolution: Full HD video with fully manual control and selectable frame rates (great for precision and high-quality video work)",
      " Connectivity: WiFi, NFC and Bluetooth built-in (useful for remotely controlling your camera and transferring pictures wirelessly as you shoot)",
      "Lens Mount: EF-S mount compatible with all EF and EF-S lenses (crop-sensor mount versatile and compact, especially when used with EF-S lenses)",
      "Country of Origin: Taiwan",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "gopro",
    title: "GoPro HERO10 Black - Front LCD and Touch Rear Screens,23MP.",
    price: 35400,
    rating: 4.5,
    totalRating: 103,
    wishlist: false,
    src1: actionCamera,
    src2: actionCamera2,
    src3: actionCamera3,
    src4: actionCamera,
    src5: actionCamera2,
    inStock: 8,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "1 year international + 1 year local India warranty. For 1 Year extended warranty please visit gopro.luxurypersonified.co.in",
      "Revolutionary Processor: Faster. Smoother. Better. The powerful new GP2 engine changes the game—snappy performance, responsive touch controls and double the frame rate for amazingly smooth footage. Designed specifically for the demanding nature of the GoPro, the GP2 “system on a chip” is by far our fastest ever.",
      "High-Res Photos + Videos, High Frame Rate: Step up to the sharpest-shooting GoPro ever. Upgraded to incredible 23MP photos and 5.3K video resolution at 60fps, HERO10 offers double the frame rate for amazingly smooth motion. Plus, there’s 8x slo-mo at 2.7K and you can pause videos and grab 15.8MP still photos from 5.3K video that look amazing.",
      "Unbelievable Image Quality: Shoot with fine detail, realistic textures and stunning contrast, even in low light. Images look their best thanks to a new water-shedding hydrophobic lens cover that repels water while helping to eliminate lens flare and other artifacts.",
      "HyperSmooth 4.0: HyperSmooth has never been smoother, and it’s easy to dial in the best stabilization at all times. Plus, get even better low-light performance and horizon leveling with a higher tilt limit, so your footage looks perfectly straight when you want it.",
      "Compatible with Over 30 Accessories",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony DSC W830 Cyber-Shot 20.1 MP Point & Shoot Camera",
    price: 10999,
    rating: 4,
    totalRating: 13,
    wishlist: false,
    src1: sonySmallCamera,
    src2: sonySmallCamera2,
    src3: sonySmallCamera3,
    src4: sonySmallCamera4,
    src5: sonySmallCamera,
    inStock: 8,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Super HAD CCD sensor with 20.1 effective megapixels : Included Components - 1 U (Including-Rechargeable battery, AC Adaptor, Multi USB Cable, Wrist Strap,User Manual)",
      "720p MP4 movie mode the camera shoots 1280 x 720 high definition movies at 30 fps, Focal length f=4.5-36mm. Exposure Compensation: +/- 2.0 EV, 1/3 EV step",
      "8x optical zoom Carl Zeiss Vario Tessar lens.Refer user manual ; Screen type: 6.7cm(2.7-type)(4:3) / 230,400 dots / ClearPhoto / TFT LCD ; Brightness Control: 5 (Bright) / 4 / 3 / 2 / 1 (Dark)",
      "Equipped with sweep panorama, intelligent auto and picture effect, Self-Timer: Off , 10sec., 2sec., portrait1, portrait2",
      "Power Consumption (Camera Mode): Approx. 1.2W; Power Source: DC3.6V (supplied battery)/DC5.0V (supplied AC adaptor)",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 6D DSLR Camera (Kit 24 - 105)  (Black)",
    price: 135100,
    rating: 3.5,
    totalRating: 40,
    wishlist: false,
    src1: canon6dCamera,
    src2: canon6dCamera2,
    src3: canon6dCamera3,
    src4: canon6dCamera4,
    src5: canon6dCamera5,
    inStock: 8,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "This camera comes with a high resolution 20.2-megapixel CMOS sensor capture sharp images with quality and detail. It has a new photodiode construction, gapless microlens array and on-chip noise reduction circuitry on the sensor to keep the image data clean and clear, even at high ISO settings.",
      "The Canon EOS 6D lets you take pictures in any environment, bright or low-lit, as it comes with a flexible ISO speed setting between 50 and 102400. It lets you adjust the camera's sensitivity to light, giving you great photos in both day and night.",
      "As the Canon EOS 6D supports IEEE 802.11 b/g/n networks, you share data between your camera and Wi-Fi enabled devices or on social networking sites. With built-in GPS tracking, you can tag the place where you took the photo with accurate GPS coordinates. You can also use your smartphone to remotely control the camera through Wi-Fi.",
      "Record high definition videos with manual exposure control and multiple frame rates. Record 1080p videos at 30 frames per second or 720p videos at 60 frames per second.",
      "High Dynamic Range lets you take high-quality videos with ease, allowing you to expand your creative mindset using various features such as Scene Intelligent Auto and Special Scene Modes to get the perfect shot.",
      "This camera is compatible with SD/SDHC/SDXC memory cards, allowing you to store more photos and videos.",
    ],
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "canon",
    title: "Canon EF 85mm f1.2L II USM Lens for Canon DSLR Cameras",
    price: 85100,
    rating: 3.2,
    totalRating: 13,
    wishlist: false,
    src1: lens85mm,
    src2: lens85mm,
    src3: lens85mm,
    src4: lens85mm,
    src5: lens85mm,
    inStock: 0,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Beautiful bokeh with DS* coating",
      "High image quality and bright f/1.2 aperture mid-telephoto zoom RF L lens.",
      "Blue spectrum refractive optics (br) Reduces chromatic aberration.",
      "Minimum focusing distance of 2.79 ft./0.85M.",
      "Control ring for direct setting changes.",
      "Lens Type: Macro",
    ],
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "papa",
    title: "Apexel 4K HD Mobile Phone 5-in-1 Camera Lens Kit",
    price: 540,
    rating: 2.2,
    totalRating: 25,
    wishlist: false,
    src1: lensForMobile,
    src2: lensForMobile2,
    src3: lensForMobile3,
    src4: lensForMobile4,
    src5: lensForMobile5,
    inStock: 0,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "The 4K HD Mobile Phone 5-in-1 Camera Lens Kit from Apexel is a bundle that contains a 2x Zoom Telephone Lens, a 0.6x / 110° Wide-Angle Lens, a 170° Super Wide-Angle Lens, a 195° Fisheye Lens, and a 10x Macro Lens. These lenses are compatible with iPhone XS Max, XR, X, 8, 7, and 6 Plus, as well as Samsung phones.",
      "This lens provides a magnification of 10x for detailed close-ups. The Telephoto Lens provides a minimum magnification of 2x to deliver photos from a distance that are of higher quality. If you'd like to create subjects with a blurred background, please keep the lens 12 to 40 from your subject. To fully utilize the 2x magnification, keep the lens at least 60 from the subject.",
      "Shoot a wide range of scenery with a magnification of 0.6x and a 110° angle of view. This lens is suitable for group selfies, travel, landscapes, and more.",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "polaroid",
    title: "Polaroid Originals Now I-Type Instant Camera - (9030)",
    price: 12999,
    rating: 2.1,
    totalRating: 14,
    wishlist: false,
    src1: polaroidCamera,
    src2: polaroidCamera2,
    src3: polaroidCamera3,
    src4: polaroidCamera4,
    src5: polaroidCamera5,
    inStock: 7,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "NOW: Polaroid's new point-and-shoot analog instant camera has all you need to catch every life moment in an original Polaroid photograph.",
      "NEW & IMPROVED: Now with autofocus, it’s simple to capture moments as you see them, so you can relive them forever in sharp, vivid color.",
      " DOUBLE EXPOSURE: Frame two moments in one with double exposure, or get yourself in the picture with self-timer and an accurate flash to make everyone look like they should.",
      "COLORFUL FUN: Now is available in the 7 colors of the iconic Polaroid spectrum.",
      " POINT. SHOOT. KEEP FOREVER: Now is compatible with both i-Type and 600 film.",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony Alpha ILCE-7RM3A Full-Frame 42.4MP Mirrorless Camera Body",
    price: 202200,
    rating: 1.6,
    totalRating: 34,
    wishlist: false,
    src1: sonyAlphaCamera,
    src2: sonyAlphaCamera2,
    src3: sonyAlphaCamera3,
    src4: sonyAlphaCamera4,
    src5: sonyAlphaCamera5,
    inStock: 7,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "35mm full-frame “Exmor R” CMOS sensor with approx 42.4 effective megapixels",
      "Enhanced BIONZ X image processing engine with front end LSI",
      "ISO sensitivity: 100 – 32000 (expandable 50 – 102400)",
      "14bit RAW format (ARW)",
      "Image sensor-shift mechanism (5-axis compensation) of a 5.5 stop compensation performance",
      "No optical low-pass filter",
      "Pixel Shift Multi Shooting",
      "Continuous shooting at up to 10 fps (with AF/AE tracking)",
      "Silent and vibration-free shooting (Electronical shutter)",
      "2 Year standard warranty + 1 year extended warranty on registration on alpha community",
      "399 points Hybrid Phase Detection AF + 425 Contrast AF",
      "Country of Origin: China",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 1500D 24.1 Digital SLR Camera EF S18-55 is II Lens",
    price: 18999,
    rating: 1.8,
    totalRating: 30,
    wishlist: false,
    src1: cameraCanon,
    src2: cameraCanon2,
    src3: cameraCanon3,
    src4: cameraCanon4,
    src5: cameraCanon5,
    inStock: 7,
    newestArrival: true,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Sensor: APS-C CMOS Sensor with 24.1 MP (high resolution for large prints and image cropping). Transmission frequency (central frequency):Frequency: 2 412 to 2 462MHz. Standard diopter :-2.5 - +0.5m-1 (dpt)",
      "ISO: 100-6400 sensitivity range (critical for obtaining grain-free pictures, especially in low light)",
      "Image Processor: DIGIC 4+ with 9 autofocus points (important for speed and accuracy of autofocus and burst photography)",
      "Video Resolution: Full HD video with fully manual control and selectable frame rates (great for precision and high-quality video work)",
      " Connectivity: WiFi, NFC and Bluetooth built-in (useful for remotely controlling your camera and transferring pictures wirelessly as you shoot)",
      "Lens Mount: EF-S mount compatible with all EF and EF-S lenses (crop-sensor mount versatile and compact, especially when used with EF-S lenses)",
      "Country of Origin: Taiwan",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "gopro",
    title: "GoPro HERO10 Black - Front LCD and Touch Rear Screens,23MP.",
    price: 35400,
    rating: 1.4,
    totalRating: 103,
    wishlist: false,
    src1: actionCamera,
    src2: actionCamera2,
    src3: actionCamera3,
    src4: actionCamera,
    src5: actionCamera2,
    inStock: 20,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "1 year international + 1 year local India warranty. For 1 Year extended warranty please visit gopro.luxurypersonified.co.in",
      "Revolutionary Processor: Faster. Smoother. Better. The powerful new GP2 engine changes the game—snappy performance, responsive touch controls and double the frame rate for amazingly smooth footage. Designed specifically for the demanding nature of the GoPro, the GP2 “system on a chip” is by far our fastest ever.",
      "High-Res Photos + Videos, High Frame Rate: Step up to the sharpest-shooting GoPro ever. Upgraded to incredible 23MP photos and 5.3K video resolution at 60fps, HERO10 offers double the frame rate for amazingly smooth motion. Plus, there’s 8x slo-mo at 2.7K and you can pause videos and grab 15.8MP still photos from 5.3K video that look amazing.",
      "Unbelievable Image Quality: Shoot with fine detail, realistic textures and stunning contrast, even in low light. Images look their best thanks to a new water-shedding hydrophobic lens cover that repels water while helping to eliminate lens flare and other artifacts.",
      "HyperSmooth 4.0: HyperSmooth has never been smoother, and it’s easy to dial in the best stabilization at all times. Plus, get even better low-light performance and horizon leveling with a higher tilt limit, so your footage looks perfectly straight when you want it.",
      "Compatible with Over 30 Accessories",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony DSC W830 Cyber-Shot 20.1 MP Point & Shoot Camera",
    price: 10999,
    rating: 3.7,
    totalRating: 13,
    wishlist: false,
    src1: sonySmallCamera,
    src2: sonySmallCamera2,
    src3: sonySmallCamera3,
    src4: sonySmallCamera4,
    src5: sonySmallCamera,
    inStock: 20,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Super HAD CCD sensor with 20.1 effective megapixels : Included Components - 1 U (Including-Rechargeable battery, AC Adaptor, Multi USB Cable, Wrist Strap,User Manual)",
      "720p MP4 movie mode the camera shoots 1280 x 720 high definition movies at 30 fps, Focal length f=4.5-36mm. Exposure Compensation: +/- 2.0 EV, 1/3 EV step",
      "8x optical zoom Carl Zeiss Vario Tessar lens.Refer user manual ; Screen type: 6.7cm(2.7-type)(4:3) / 230,400 dots / ClearPhoto / TFT LCD ; Brightness Control: 5 (Bright) / 4 / 3 / 2 / 1 (Dark)",
      "Equipped with sweep panorama, intelligent auto and picture effect, Self-Timer: Off , 10sec., 2sec., portrait1, portrait2",
      "Power Consumption (Camera Mode): Approx. 1.2W; Power Source: DC3.6V (supplied battery)/DC5.0V (supplied AC adaptor)",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 6D DSLR Camera (Kit 24 - 105)  (Black)",
    price: 135100,
    rating: 4.5,
    totalRating: 40,
    wishlist: false,
    src1: canon6dCamera,
    src2: canon6dCamera2,
    src3: canon6dCamera3,
    src4: canon6dCamera4,
    src5: canon6dCamera5,
    inStock: 20,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "This camera comes with a high resolution 20.2-megapixel CMOS sensor capture sharp images with quality and detail. It has a new photodiode construction, gapless microlens array and on-chip noise reduction circuitry on the sensor to keep the image data clean and clear, even at high ISO settings.",
      "The Canon EOS 6D lets you take pictures in any environment, bright or low-lit, as it comes with a flexible ISO speed setting between 50 and 102400. It lets you adjust the camera's sensitivity to light, giving you great photos in both day and night.",
      "As the Canon EOS 6D supports IEEE 802.11 b/g/n networks, you share data between your camera and Wi-Fi enabled devices or on social networking sites. With built-in GPS tracking, you can tag the place where you took the photo with accurate GPS coordinates. You can also use your smartphone to remotely control the camera through Wi-Fi.",
      "Record high definition videos with manual exposure control and multiple frame rates. Record 1080p videos at 30 frames per second or 720p videos at 60 frames per second.",
      "High Dynamic Range lets you take high-quality videos with ease, allowing you to expand your creative mindset using various features such as Scene Intelligent Auto and Special Scene Modes to get the perfect shot.",
      "This camera is compatible with SD/SDHC/SDXC memory cards, allowing you to store more photos and videos.",
    ],
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "canon",
    title: "Canon EF 85mm f1.2L II USM Lens for Canon DSLR Cameras",
    price: 85100,
    rating: 4,
    totalRating: 13,
    wishlist: false,
    src1: lens85mm,
    src2: lens85mm,
    src3: lens85mm,
    src4: lens85mm,
    src5: lens85mm,
    inStock: 10,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Beautiful bokeh with DS* coating",
      "High image quality and bright f/1.2 aperture mid-telephoto zoom RF L lens.",
      "Blue spectrum refractive optics (br) Reduces chromatic aberration.",
      "Minimum focusing distance of 2.79 ft./0.85M.",
      "Control ring for direct setting changes.",
      "Lens Type: Macro",
    ],
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "papa",
    title: "Apexel 4K HD Mobile Phone 5-in-1 Camera Lens Kit",
    price: 299,
    rating: 2.6,
    totalRating: 25,
    wishlist: false,
    src1: lensForMobile,
    src2: lensForMobile2,
    src3: lensForMobile3,
    src4: lensForMobile4,
    src5: lensForMobile5,
    inStock: 10,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "The 4K HD Mobile Phone 5-in-1 Camera Lens Kit from Apexel is a bundle that contains a 2x Zoom Telephone Lens, a 0.6x / 110° Wide-Angle Lens, a 170° Super Wide-Angle Lens, a 195° Fisheye Lens, and a 10x Macro Lens. These lenses are compatible with iPhone XS Max, XR, X, 8, 7, and 6 Plus, as well as Samsung phones.",
      "This lens provides a magnification of 10x for detailed close-ups. The Telephoto Lens provides a minimum magnification of 2x to deliver photos from a distance that are of higher quality. If you'd like to create subjects with a blurred background, please keep the lens 12 to 40 from your subject. To fully utilize the 2x magnification, keep the lens at least 60 from the subject.",
      "Shoot a wide range of scenery with a magnification of 0.6x and a 110° angle of view. This lens is suitable for group selfies, travel, landscapes, and more.",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "polaroid",
    title: "Polaroid Originals Now I-Type Instant Camera - (9030)",
    price: 12999,
    rating: 4.3,
    totalRating: 14,
    wishlist: false,
    src1: polaroidCamera,
    src2: polaroidCamera2,
    src3: polaroidCamera3,
    src4: polaroidCamera4,
    src5: polaroidCamera5,
    inStock: 5,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "NOW: Polaroid's new point-and-shoot analog instant camera has all you need to catch every life moment in an original Polaroid photograph.",
      "NEW & IMPROVED: Now with autofocus, it’s simple to capture moments as you see them, so you can relive them forever in sharp, vivid color.",
      " DOUBLE EXPOSURE: Frame two moments in one with double exposure, or get yourself in the picture with self-timer and an accurate flash to make everyone look like they should.",
      "COLORFUL FUN: Now is available in the 7 colors of the iconic Polaroid spectrum.",
      " POINT. SHOOT. KEEP FOREVER: Now is compatible with both i-Type and 600 film.",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony Alpha ILCE-7RM3A Full-Frame 42.4MP Mirrorless Camera Body",
    price: 202900,
    rating: 3.7,
    totalRating: 34,
    wishlist: false,
    src1: sonyAlphaCamera,
    src2: sonyAlphaCamera2,
    src3: sonyAlphaCamera3,
    src4: sonyAlphaCamera4,
    src5: sonyAlphaCamera5,
    inStock: 6,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "35mm full-frame “Exmor R” CMOS sensor with approx 42.4 effective megapixels",
      "Enhanced BIONZ X image processing engine with front end LSI",
      "ISO sensitivity: 100 – 32000 (expandable 50 – 102400)",
      "14bit RAW format (ARW)",
      "Image sensor-shift mechanism (5-axis compensation) of a 5.5 stop compensation performance",
      "No optical low-pass filter",
      "Pixel Shift Multi Shooting",
      "Continuous shooting at up to 10 fps (with AF/AE tracking)",
      "Silent and vibration-free shooting (Electronical shutter)",
      "2 Year standard warranty + 1 year extended warranty on registration on alpha community",
      "399 points Hybrid Phase Detection AF + 425 Contrast AF",
      "Country of Origin: China",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 1500D 24.1 Digital SLR Camera EF S18-55 is II Lens",
    price: 18999,
    rating: 1.2,
    totalRating: 30,
    wishlist: false,
    src1: cameraCanon,
    src2: cameraCanon2,
    src3: cameraCanon3,
    src4: cameraCanon4,
    src5: cameraCanon5,
    inStock: 7,
    newestArrival: false,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "Sensor: APS-C CMOS Sensor with 24.1 MP (high resolution for large prints and image cropping). Transmission frequency (central frequency):Frequency: 2 412 to 2 462MHz. Standard diopter :-2.5 - +0.5m-1 (dpt)",
      "ISO: 100-6400 sensitivity range (critical for obtaining grain-free pictures, especially in low light)",
      "Image Processor: DIGIC 4+ with 9 autofocus points (important for speed and accuracy of autofocus and burst photography)",
      "Video Resolution: Full HD video with fully manual control and selectable frame rates (great for precision and high-quality video work)",
      " Connectivity: WiFi, NFC and Bluetooth built-in (useful for remotely controlling your camera and transferring pictures wirelessly as you shoot)",
      "Lens Mount: EF-S mount compatible with all EF and EF-S lenses (crop-sensor mount versatile and compact, especially when used with EF-S lenses)",
      "Country of Origin: Taiwan",
    ],
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "gopro",
    title: "GoPro HERO10 Black - Front LCD and Touch Rear Screens,23MP.",
    price: 35400,
    rating: 4.5,
    totalRating: 103,
    wishlist: false,
    src1: actionCamera,
    src2: actionCamera2,
    src3: actionCamera3,
    src4: actionCamera,
    src5: actionCamera2,
    inStock: 5,
    newestArrival: true,
    delivery: `${Math.trunc(Math.random() * 10) + 2} Days`,
    description: [
      "1 year international + 1 year local India warranty. For 1 Year extended warranty please visit gopro.luxurypersonified.co.in",
      "Revolutionary Processor: Faster. Smoother. Better. The powerful new GP2 engine changes the game—snappy performance, responsive touch controls and double the frame rate for amazingly smooth footage. Designed specifically for the demanding nature of the GoPro, the GP2 “system on a chip” is by far our fastest ever.",
      "High-Res Photos + Videos, High Frame Rate: Step up to the sharpest-shooting GoPro ever. Upgraded to incredible 23MP photos and 5.3K video resolution at 60fps, HERO10 offers double the frame rate for amazingly smooth motion. Plus, there’s 8x slo-mo at 2.7K and you can pause videos and grab 15.8MP still photos from 5.3K video that look amazing.",
      "Unbelievable Image Quality: Shoot with fine detail, realistic textures and stunning contrast, even in low light. Images look their best thanks to a new water-shedding hydrophobic lens cover that repels water while helping to eliminate lens flare and other artifacts.",
      "HyperSmooth 4.0: HyperSmooth has never been smoother, and it’s easy to dial in the best stabilization at all times. Plus, get even better low-light performance and horizon leveling with a higher tilt limit, so your footage looks perfectly straight when you want it.",
      "Compatible with Over 30 Accessories",
    ],
  },
];

export { products };
