import { v4 as uuid } from "uuid";
import {
  lens85mm,
  actionCamera,
  cameraCanon,
  canon6dCamera,
  lensForMobile,
  polaroidCamera,
  sonyAlphaCamera,
  sonySmallCamera,
} from "../../Data/Img/Products/ProductImages";

/*
  Product Database 
*/

const products = [
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony DSC W830 Cyber-Shot 20.1 MP Point & Shoot Camera",
    price: 10999,
    rating: 4,
    totalRating: 13,
    wishlist: false,
    src: sonySmallCamera,
    inStock: 20,
    newestArrival: true,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 6D DSLR Camera (Kit 24 - 105)  (Black)",
    price: 135100,
    rating: 4.5,
    totalRating: 40,
    wishlist: false,
    src: canon6dCamera,
    inStock: 13,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "canon",
    title: "Canon EF 85mm f1.2L II USM Lens for Canon DSLR Cameras",
    price: 85100,
    rating: 4.2,
    totalRating: 13,
    wishlist: false,
    src: lens85mm,
    inStock: 3,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "papa",
    title: "LUZWE 3in1 Lens Kit for all Smartphone, iOS Devices & Tablets",
    price: 350,
    rating: 1,
    totalRating: 25,
    wishlist: false,
    src: lensForMobile,
    inStock: 0,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "polaroid",
    title: "Polaroid Originals Now I-Type Instant Camera - (9030)",
    price: 12999,
    rating: 1.8,
    totalRating: 14,
    wishlist: false,
    src: polaroidCamera,
    inStock: 4,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony Alpha ILCE-7RM3A Full-Frame 42.4MP Mirrorless Camera Body",
    price: 202900,
    rating: 2.8,
    totalRating: 34,
    wishlist: false,
    src: sonyAlphaCamera,
    inStock: 12,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 1500D 24.1 Digital SLR Camera EF S18-55 is II Lens",
    price: 18999,
    rating: 3.5,
    totalRating: 30,
    wishlist: false,
    src: cameraCanon,
    inStock: 0,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "gopro",
    title: "GoPro HERO10 Black - Front LCD and Touch Rear Screens,23MP.",
    price: 35400,
    rating: 4.5,
    totalRating: 103,
    wishlist: false,
    src: actionCamera,
    inStock: 10,
    newestArrival: true,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony DSC W830 Cyber-Shot 20.1 MP Point & Shoot Camera",
    price: 10999,
    rating: 4.8,
    totalRating: 13,
    wishlist: false,
    src: sonySmallCamera,
    inStock: 0,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 6D DSLR Camera (Kit 24 - 105)  (Black)",
    price: 135100,
    rating: 3.3,
    totalRating: 40,
    wishlist: false,
    src: canon6dCamera,
    inStock: 6,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "canon",
    title: "Canon EF 85mm f1.2L II USM Lens for Canon DSLR Cameras",
    price: 85100,
    rating: 3.2,
    totalRating: 13,
    wishlist: false,
    src: lens85mm,
    inStock: 7,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "papa",
    title: "LUZWE 3in1 Lens Kit for all Smartphone, iOS Devices & Tablets",
    price: 299,
    rating: 2.7,
    totalRating: 25,
    wishlist: false,
    src: lensForMobile,
    inStock: 6,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "polaroid",
    title: "Polaroid Originals Now I-Type Instant Camera - (9030)",
    price: 12999,
    rating: 2.6,
    totalRating: 14,
    wishlist: false,
    src: polaroidCamera,
    inStock: 3,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony Alpha ILCE-7RM3A Full-Frame 42.4MP Mirrorless Camera Body",
    price: 202900,
    rating: 4.7,
    totalRating: 34,
    wishlist: false,
    src: sonyAlphaCamera,
    inStock: 4,
    newestArrival: true,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 1500D 24.1 Digital SLR Camera EF S18-55 is II Lens",
    price: 18999,
    rating: 2.5,
    totalRating: 30,
    wishlist: false,
    src: cameraCanon,
    inStock: 5,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "gopro",
    title: "GoPro HERO10 Black - Front LCD and Touch Rear Screens,23MP.",
    price: 35400,
    rating: 4.5,
    totalRating: 103,
    wishlist: false,
    src: actionCamera,
    inStock: 8,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony DSC W830 Cyber-Shot 20.1 MP Point & Shoot Camera",
    price: 10999,
    rating: 4,
    totalRating: 13,
    wishlist: false,
    src: sonySmallCamera,
    inStock: 8,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 6D DSLR Camera (Kit 24 - 105)  (Black)",
    price: 135100,
    rating: 3.5,
    totalRating: 40,
    wishlist: false,
    src: canon6dCamera,
    inStock: 8,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "canon",
    title: "Canon EF 85mm f1.2L II USM Lens for Canon DSLR Cameras",
    price: 85100,
    rating: 3.2,
    totalRating: 13,
    wishlist: false,
    src: lens85mm,
    inStock: 0,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "papa",
    title: "LUZWE 3in1 Lens Kit for all Smartphone, iOS Devices & Tablets",
    price: 540,
    rating: 2.2,
    totalRating: 25,
    wishlist: false,
    src: lensForMobile,
    inStock: 0,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "polaroid",
    title: "Polaroid Originals Now I-Type Instant Camera - (9030)",
    price: 12999,
    rating: 2.1,
    totalRating: 14,
    wishlist: false,
    src: polaroidCamera,
    inStock: 7,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony Alpha ILCE-7RM3A Full-Frame 42.4MP Mirrorless Camera Body",
    price: 202200,
    rating: 1.6,
    totalRating: 34,
    wishlist: false,
    src: sonyAlphaCamera,
    inStock: 7,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 1500D 24.1 Digital SLR Camera EF S18-55 is II Lens",
    price: 18999,
    rating: 1.8,
    totalRating: 30,
    wishlist: false,
    src: cameraCanon,
    inStock: 7,
    newestArrival: true,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "gopro",
    title: "GoPro HERO10 Black - Front LCD and Touch Rear Screens,23MP.",
    price: 35400,
    rating: 1.4,
    totalRating: 103,
    wishlist: false,
    src: actionCamera,
    inStock: 20,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony DSC W830 Cyber-Shot 20.1 MP Point & Shoot Camera",
    price: 10999,
    rating: 3.7,
    totalRating: 13,
    wishlist: false,
    src: sonySmallCamera,
    inStock: 20,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 6D DSLR Camera (Kit 24 - 105)  (Black)",
    price: 135100,
    rating: 4.5,
    totalRating: 40,
    wishlist: false,
    src: canon6dCamera,
    inStock: 20,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "canon",
    title: "Canon EF 85mm f1.2L II USM Lens for Canon DSLR Cameras",
    price: 85100,
    rating: 4,
    totalRating: 13,
    wishlist: false,
    src: lens85mm,
    inStock: 10,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "lens",
    brand: "papa",
    title: "LUZWE 3in1 Lens Kit for all Smartphone, iOS Devices & Tablets",
    price: 299,
    rating: 2.6,
    totalRating: 25,
    wishlist: false,
    src: lensForMobile,
    inStock: 10,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "polaroid",
    title: "Polaroid Originals Now I-Type Instant Camera - (9030)",
    price: 12999,
    rating: 4.3,
    totalRating: 14,
    wishlist: false,
    src: polaroidCamera,
    inStock: 5,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "sony",
    title: "Sony Alpha ILCE-7RM3A Full-Frame 42.4MP Mirrorless Camera Body",
    price: 202900,
    rating: 3.7,
    totalRating: 34,
    wishlist: false,
    src: sonyAlphaCamera,
    inStock: 6,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "canon",
    title: "Canon EOS 1500D 24.1 Digital SLR Camera EF S18-55 is II Lens",
    price: 18999,
    rating: 1.2,
    totalRating: 30,
    wishlist: false,
    src: cameraCanon,
    inStock: 7,
    newestArrival: false,
  },
  {
    _id: uuid(),
    category: "camera",
    brand: "gopro",
    title: "GoPro HERO10 Black - Front LCD and Touch Rear Screens,23MP.",
    price: 35400,
    rating: 4.5,
    totalRating: 103,
    wishlist: false,
    src: actionCamera,
    inStock: 5,
    newestArrival: true,
  },
];

export { products };
